flow = "automatic_chisel_vivado"

project_root = "qece-benchmark"

target_file = "src/main/scala/generation/explore/FftExplore.scala"

task_file = "exploration_files/fft_exploration_file.toml" # if csv we go points mode, if toml we go space mode

board = "xc7z020clg484-1"

clock_port = "clock"

custom_metrics_folder = "custom_metrics"

verbose = true

[metrics]
default = ["Slice LUTs*","Slice Registers","Block RAM Tile","DSPs","frequency"]
custom=["fft_throughput"]

[extra]
[extra.generate]
command = "bash ../make_fft.bash" # the command is ran from the work directory
# the above script generates rocket chip verilog and puts it into a chisel_generated folder inside the working directory
project_root = "chisel_generated" # this is given with respect to dovado_work
target_file = "FftWrapper2.v" # generated file containing target module relative to root
target_module = "FftWrapper2"
