flow = "manual_hls_vitis"

project_root = "01-convolution-tutorial/src/"

target_file = "filter2d_hw.cpp"

task_file = "exploration_files/filter_exploration_file.csv"

board = "xc7k70tfbv676-1"

clock_port = "ap_clk" # refers to the clock port of the generated module

custom_metrics_folder = "custom_metrics"

[metrics]
default = ["Slice LUTs*", "Block RAM Tile", "DSPs", "frequency"]
custom=[]

target_module = "Filter2DKernel_Filter2D"

[extra]
[extra.vitis]
project_root = "solution1/syn/verilog"
target_file = "Filter2DKernel_Filter2D.v"
target_clock = 250
target_module = "Filter2DKernel"
